# docker-compose.yml
version: "3"
services:
  database:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=9IWiMbwXui4Rx8u9Z3JdCopy
      - POSTGRES_DB=glee
    ports:
      - "5532:5432"
