# docker-compose.yml
version: "3"
services:
  database:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=RSifA86xHz5DZb0zdfKYCopy
      - POSTGRES_DB=glee
    ports:
      - "5532:5432"
